### ISSUE TITLE
Support for REST http/https

### ISSUE THREAD

**Issue by n-pafitis** [sjkummer/janus-gateway-js#105]
From my knowledge this library only supports websocket connections, is it possible to add support for the REST api through http/https?

**Comment by sjkummer** [comment]
Hi there,

This is not on my roadmap at the moment, but Pull-Requests are welcome.

**Comment by sjkummer** [comment]
For the sake of completeness: Docs about how to use the original JavaScript API that comes as part of Janus itself (janus.js) can be found here: https://janus.conf.meetecho.com/docs/JS.html

**Comment by uwejan** [comment]
@sjkummer Will it be possible to use mqtt instead of ws?

**Comment by sjkummer** [comment]
> @sjkummer Will it be possible to use mqtt instead of ws?

@uwejan Implementing MQTT is not on my roadmap. Implementing different transport types to execute the same Janus request does not really add value to this library. Websockets are enabled by default anyway.
