### ISSUE TITLE
Can i use it for React Native

### ISSUE THREAD

**Issue by haddad-yacine** [sjkummer/janus-gateway-js#109]
if not, is there any alternative for react native please ?

**Comment by Namec** [comment]
hello Yacine, 

have you found a response to your question, i am wondering if this package is still maintained

**Comment by haddad-yacine** [comment]
Hello @Namec 

No, i didn't found any response for that.

**Comment by Namec** [comment]
i am trying to integrate this with reactjs, but it's missing a lot of api's like textroom.

i juste found this, if it can help you :
https://github.com/atyenoria/react-native-webrtc-janus-gateway

**Comment by haddad-yacine** [comment]
Thank you @Namec, as you can see , that repository is no more maintained 3 years ago.

**Comment by Namec** [comment]
nothing better unfortunatly.

if you found something just tell your algerian bro ;-)

**Comment by Namec** [comment]
@haddad-yacine 

https://github.com/MinesNicaicai/janus-webrtc-react-native

**Comment by haddad-yacine** [comment]
Thank you @Namec , but as you can see that project is based on the same lib Janus in: https://github.com/atyenoria/react-native-webrtc-janus-gateway

**Comment by sjkummer** [comment]
You can use this library to communicate to Janus. How you build your UI is up to you. The MediaPlugins help you to handle the WebRTC / PeerConnection stuff.

**Comment by JeroenVanSteijn** [comment]
https://github.com/BytecodeAgency/janus-gateway-rn
