### ISSUE TITLE
plugin.textroom issue

### ISSUE THREAD

**Issue by Namec** [sjkummer/janus-gateway-js#110]
Hello All,

i succeeded to connect and attache to textroom plugin.

but i don't found a way to list rooms, it says that i am missing request data !!!

here is my code : 

    janus.createConnection('id').then(function(connection) {
      connection.createSession().then(function(session) {
        session.attachPlugin('janus.plugin.textroom').then(function(plugin) {
          plugin.send({
            "janus":"message",
            "body":{"request":"setup"}
          }).then(function(response){});
          plugin.send({
            "janus":"message",
            "body":{ "textroom":"list" }
          }).then(function(response){});
        });
      });
    });

thanks

**Comment by sjkummer** [comment]
This library currently offers the following plugins:
https://github.com/sjkummer/janus-gateway-js/tree/master/src/webrtc/plugin

If you want to implement your own plugin, make sure to read https://github.com/sjkummer/janus-gateway-js#how-to-write-a-plugin

You also may want to send messages to janus directly using the session object (without a plugin).

The API to the janus TextRoom plugin is documented here: https://janus.conf.meetecho.com/docs/textroom.html

**Comment by webpolis** [comment]
> Hello All,
> 
> i succeeded to connect and attache to textroom plugin.
> 
> but i don't found a way to list rooms, it says that i am missing request data !!!
> 
> here is my code :
> 
> ```
> janus.createConnection('id').then(function(connection) {
>   connection.createSession().then(function(session) {
>     session.attachPlugin('janus.plugin.textroom').then(function(plugin) {
>       plugin.send({
>         "janus":"message",
>         "body":{"request":"setup"}
>       }).then(function(response){});
>       plugin.send({
>         "janus":"message",
>         "body":{ "textroom":"list" }
>       }).then(function(response){});
>     });
>   });
> });
> ```
> 
> thanks

any solution here?

**Comment by sjkummer** [comment]
Listing the Janus TextRooms works as follows:
```
import Janus from 'janus-gateway-js'

var janus = new Janus.Client('ws://localhost:8188', {
    token: 'token',
    apisecret: 'apisecret',
    keepalive: 'true'
});

janus.createConnection('id').then(function(connection) {
    connection.createSession().then(function(session) {
        session.attachPlugin('janus.plugin.textroom').then(function(plugin) {
            const message = {
                body: {
                    request: "list",
                    textroom : "list",
                }
            };
            plugin.sendWithTransaction(message).then(function(response){
                const plainMessage = response.getPlainMessage();
                const list = plainMessage.plugindata.data.list;
                console.log(list);
            }).catch(e => {
                console.error(e);
            });
        });
    });
});
```

This will print something like:
```
[
  {
    room: 1234,
    description: 'Demo Room',
    pin_required: false,
    num_participants: 0
  }
]
```

If you want to do the setup request yourself, you also have to pass & handle all the WebRTC / Peerconnection stuff yourself. It's probably easier to add a plugin for that at https://github.com/sjkummer/janus-gateway-js/tree/master/src/webrtc/plugin and utilise the basic media / Peerconnection implementation.
Be aware that sending chat messages in the Janus TextRoom uses a WebRTC Datachannel.
