### ISSUE TITLE
Running on node?

### ISSUE THREAD

**Issue by rygo6** [sjkummer/janus-gateway-js#114]
I am having some trouble figuring out how to get this to work on node. I notice in your readme there are mentions of this throughout, but it seems like running on node needs some extra steps other than just do npm/yarn install. Could you write out some more detail instructions specifically for node?

It looks like I need to cd into the janus-gateway-js folder in node and run gulp? Then configure a third party webrtc adaptor? Is that correct for node use?

**Comment by sjkummer** [comment]
Installing this library Node ist supported. Just run:
`npm i janus-gateway-js`

On node, there will be no UI or similar. The lib then just provides an easy way to communicate to the Janus API.

https://www.npmjs.com/package/janus-gateway-js
