### ISSUE TITLE
Is there a current way to get all sessions on a janus instance?

### ISSUE THREAD

**Issue by GRVYDEV** [sjkummer/janus-gateway-js#116]
Hi, I am wondering if there is a way to get all of the current connections on a single janus instance. I need to build a CDN system for janus and I would like to be able to see how many people are connected to the server.

**Comment by sjkummer** [comment]
You are probably looking for the `list_sessions`  request of the Janus Admin API: https://janus.conf.meetecho.com/docs/admin.html

Calling an additional request using library can be done, but you will need to parse the result JSON by yourself.
